/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessRequest {
  'id' : bigint,
  'status' : string,
  'resourceName' : string,
  'requesterName' : string,
  'requestType' : string,
  'requestedAt' : string,
  'resolvedAt' : string,
  'resolvedBy' : string,
  'reason' : string,
}
export interface AuditLog {
  'id' : bigint,
  'status' : string,
  'userName' : string,
  'resource' : string,
  'action' : string,
  'timestamp' : string,
  'ipAddress' : string,
}
export interface Permission {
  'id' : bigint,
  'resource' : string,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface Policy {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : string,
  'description' : string,
  'priority' : bigint,
  'rules' : string,
}
export interface Role {
  'id' : bigint,
  'permissions' : Array<string>,
  'name' : string,
  'createdAt' : string,
  'memberCount' : bigint,
  'description' : string,
}
export interface User {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : string,
  'role' : string,
  'email' : string,
  'department' : string,
  'lastLogin' : string,
}
export interface _SERVICE {
  'createAccessRequest' : ActorMethod<[string, string, string, string], bigint>,
  'createPolicy' : ActorMethod<[string, string, string, bigint], bigint>,
  'createRole' : ActorMethod<[string, string], bigint>,
  'createUser' : ActorMethod<[string, string, string, string], bigint>,
  'getAccessRequests' : ActorMethod<[], Array<AccessRequest>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getPermissions' : ActorMethod<[], Array<Permission>>,
  'getPolicies' : ActorMethod<[], Array<Policy>>,
  'getRoles' : ActorMethod<[], Array<Role>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'updateAccessRequestStatus' : ActorMethod<
    [bigint, string, string],
    undefined
  >,
  'updatePolicyStatus' : ActorMethod<[bigint, string], undefined>,
  'updateUserStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];