/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccessRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'resourceName' : IDL.Text,
  'requesterName' : IDL.Text,
  'requestType' : IDL.Text,
  'requestedAt' : IDL.Text,
  'resolvedAt' : IDL.Text,
  'resolvedBy' : IDL.Text,
  'reason' : IDL.Text,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'userName' : IDL.Text,
  'resource' : IDL.Text,
  'action' : IDL.Text,
  'timestamp' : IDL.Text,
  'ipAddress' : IDL.Text,
});
export const Permission = IDL.Record({
  'id' : IDL.Nat,
  'resource' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const Policy = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'description' : IDL.Text,
  'priority' : IDL.Nat,
  'rules' : IDL.Text,
});
export const Role = IDL.Record({
  'id' : IDL.Nat,
  'permissions' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
  'lastLogin' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAccessRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createPolicy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAccessRequests' : IDL.Func([], [IDL.Vec(AccessRequest)], ['query']),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getPermissions' : IDL.Func([], [IDL.Vec(Permission)], ['query']),
  'getPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
  'getRoles' : IDL.Func([], [IDL.Vec(Role)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'updateAccessRequestStatus' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updatePolicyStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateUserStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccessRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'resourceName' : IDL.Text,
    'requesterName' : IDL.Text,
    'requestType' : IDL.Text,
    'requestedAt' : IDL.Text,
    'resolvedAt' : IDL.Text,
    'resolvedBy' : IDL.Text,
    'reason' : IDL.Text,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'userName' : IDL.Text,
    'resource' : IDL.Text,
    'action' : IDL.Text,
    'timestamp' : IDL.Text,
    'ipAddress' : IDL.Text,
  });
  const Permission = IDL.Record({
    'id' : IDL.Nat,
    'resource' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const Policy = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'description' : IDL.Text,
    'priority' : IDL.Nat,
    'rules' : IDL.Text,
  });
  const Role = IDL.Record({
    'id' : IDL.Nat,
    'permissions' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
    'lastLogin' : IDL.Text,
  });
  
  return IDL.Service({
    'createAccessRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createPolicy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAccessRequests' : IDL.Func([], [IDL.Vec(AccessRequest)], ['query']),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getPermissions' : IDL.Func([], [IDL.Vec(Permission)], ['query']),
    'getPolicies' : IDL.Func([], [IDL.Vec(Policy)], ['query']),
    'getRoles' : IDL.Func([], [IDL.Vec(Role)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'updateAccessRequestStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePolicyStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateUserStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };